<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Reminder Kontrak</title>
</head>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
    <div style="text-align: center; border-bottom: 2px solid #e5e5e5; padding-bottom: 20px; margin-bottom: 20px;">
        @if(isset($logoPath) && file_exists($logoPath))
            <img src="{{ $message->embed($logoPath) }}" alt="{{ \App\Models\Setting::get('app_name', 'PKS Tracking System') }}" style="max-width: 200px; height: auto;">
        @else
            <h2 style="margin: 0; color: #333;">{{ \App\Models\Setting::get('app_name', 'PKS Tracking System') }}</h2>
        @endif
    </div>
    
    {{-- Dynamic email body from settings --}}
    <div style="background: #f9fafb; border-radius: 8px; padding: 20px; margin-bottom: 20px; white-space: pre-wrap;">
        {!! nl2br(e($emailBody)) !!}
    </div>



    <div style="border-top: 1px solid #e5e7eb; padding-top: 20px; margin-top: 20px; font-size: 12px; color: #6b7280;">
        <p>This email is automatically generated by the {{ \App\Models\Setting::get('app_name', 'PKS Tracking System') }}.</p>
        <p>If you believe you have received this email in error or wish to stop receiving notifications, please contact the system administrator.</p>
    </div>
</body>
</html>
